title: Tan Ren Cie # your name (or website title) here
logo: "/images/nic_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  <br><br>
  Second description 
  <br><br>

  
theme: jekyll-theme-minimal
google_analytics: UA-145918896-1 # your Google Analytics tracking ID here
