title: Tan Ren Cie # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Currently a Year 2 business student in NUS. This website is an archive of the projects that I have done.
  <br><br>
  My interest is in the education industry and business development. I'm currently interning in a promising startup, Classfront, as their Business Development/Analytics Intern. 
  <br><br>

  
  
  
  
  
  
  
theme: jekyll-theme-minimal
google_analytics: UA-145918896-1 # your Google Analytics tracking ID here
